{% set name = "ntbtls" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: bdfcb99024acec9c6c4b998ad63bb3921df4cfee4a772ad6c0ca324dbbf2b07c

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('ntbtls') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - libksba
    - libgcrypt

about:
  home: https://www.gnupg.org/software/ntbtls/index.html
  dev_url: https://github.com/gpg/ntbtls
  doc_url: https://www.gnupg.org/software/ntbtls/index.html
  summary: Not Too Bad TLS
  license: GPL-3.0-only
  license_family: GPL3
  license_file: COPYING
  description: |
    ntbTLS is a tiny TLS 1.2 only implementation designed to be used with Libgcrypt
    and LibKSBA. In particular, this library has no certificate verification code
    - this need to be done by the caller. For example the GnuPG component dirmngr
    already has code to verify certificates (for CRL and OCSP checking) and thus
    ntbTLS is a good fit for accessing objects over the network.
extra:
  recipe-maintainers:
    - zklaus
    - mariusvniekerk
  skip-lints:
    - missing_tests
