appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: If2/l7XGr6izTVPZRWubEEFWarm7/wte3zfk/MqZn9kz94Dw8ikaLx5jyUhLpM4hoJbxqMEd01tNJBCJrfVmrQ1kdOeq1RJ8omlU5k9jkRSLEE1AV0/HYjfd6D7/h8y1LmNl1F6dlX06F5zo5rcoCc0nldM3faYDX0VH2jqQn1HHjziZBS8JpAB0OS3wUX1+uXIKGj9jRqCRIOKm/pcVCOtwRNoSOSwxd/wLxaxHzeMGc96BWA6Vvj5wOBZgGIDoeY8K5JRu/Wf2UeLFrI7tBjSizgQxNGDRkOuG+UCiyz0+b0BlPTnnYIdo2TdbcXCl+0ubUiWU0hhyzKhZiy6vulT1aScfTZszoNzRmMjLin+4Zeruj3Ekcl8aHLwTX2vZOSxgb418EH2Hz3gKMPMXdDKkP5yXiDLnznxF4QvS8u8UA/003EHuGbNlL8P5Szf7ppg2ZGygQMEH1F+YXzkRkiYz4YjzUDkE+dUWRBDMjHkUejFESLuvJ3OfzzYH5d3Q0unOo5d/JA6XmMV8Fie67wdy+7Y77EVIpk1RxJCeqc5odK1RlJ4U/99zmt6TAdtMN5dqivHg/NPhB+Ie6Y0RP7xWWMulpLysWNnPHWpi/SEvo2okWMh21AoHdLL3cvw5IsYwEJrZcrckh32neRcwGwJ+iTj2A6z9jxc9J+8lrlY=}
