travis:
  secure:
    BINSTAR_TOKEN: F9x8tIz2eZ7HsH+LXenYIC4DJo3yQbzcg367Q4kYpmj4hHmtUfsTBzwk/MD5664TboO7KpOph2THO7JVh8mXIAqqsLsanBpowQGy+KlW/pIV0pYMG4km+2xomp17VBwEf53cqVw8lC5FgueWyMC9ItoDRq1C92fzRJXeND9znGBzyktqXLNrBQ2RXATvgCIvLNlL/VWhoaDO/Dc5/UFKxWLswl9gq96znGAZK5RTZi0zJCvX6k6AuqgdEOUiJ5+rxy4UwGNUx1YM+8CoJHHMf18sT3k4EZ89Iiphwqy3+vVHgY/opTukHRDIVZlM7VF0zoxwSQqGreN83PflZy+nQ7Xwoo1yLd9VoU64HNoTakz/dsmFJyS8GHYMHSLOoNyaP4R+UMrIJa79QtE0lQ2CLhdxRdzL9JheWDX1ggYfw76ydz4/uF6b3yzmA1akHNmovnJ2i1uVEi87k1wrZxucJTWZmV8CRvRjv6iyBxko2JFgzugbBQhUt3JBwuXW1ujuxt2xxb+QMRL6klqwEh7nACVZOczfCCBxcpekncyAlQVB1gslvlhl/AV7VMaoq+ncKmBrYHX7wXa9lAjN6zatZJdpCGSBRwkgwmhvwvZIGjEp2rPZVE4hT8uW5o+BTF/4GnhEOUjws1400/zZH5zuVFgWbJc/0/pTMmjiA+cmlZc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
