travis:
  secure:
    BINSTAR_TOKEN: cGLmcl+3ErTpC7JSk/x9S5//Y9vroj1hVvSBIXktD2/k5zJjhskuoolLQr4iBRL+UV9Rtw1X9qBfIh8QTbBfF2M4f5LemHM4KsJynn4eXNElYx4G6wubTvLKvA+Bp1yLqxrlXKsDG0VWkLqME3G9M6ekgbywZJaja7h+UT0DDxMbwOHQoo8ro3/AIpvUJcVtAxTchVHB87DqBaxHud0eIzC2BxrtE2odT+XtWh1YaiPOuxc6P0CffSC4hrGBj8sB69U9MnQ+psxHiSddpL+m6kVXEveGyTeCD4WpbZhlHZbYp+MmOkwiKdBY+2329/Itsbb7HjE8DJsfXTNLYuGGKPf3tXgEWfcpT9wX/nHkjT4k/NCAbJeR60tKsbG4e0IjuSY3PAurtrITYcskGypfV1Zc+W/DVj9CfdJ2Uvoi6HUswexm1pl/RmU5VPI5tRaZojD4kPvJ83OypxSF5aljdLve+NlrM78clwEsoYI+dfRuvHTdK10f6lQW0MX5uSTsDWMDJf9+Z6dQ1IMNk9aGmg7mjXusRpCSgLt+7OeMnGe9rO7WHrwkoSL8HSPa8M3sxiC16f1HXMxHlb2oVfOZIa58Jdjy/A1zIpJfFc2DNsfxoaVupSBKlSck2kx3M6FLXzSATxOc9A8BSQXfraHq1SQZMNX4Zr4sa0CknmRSk50=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
